#! /bin/bash
#
# $Author$
# $Date$ 
# $HeadUrl$ 
# $Revision$
if (( $# != 2 ))
then
    echo "usage: sesor_sum.sh <file_name>"
   # exit 0
fi
echo $@
if [[ -e $2 ]]
then
    read -p "$2 exists. Would you like to delete it? (y/n)" ans
    read -p "Enter new file name: " name
fi
echo $ans
echo $name
exit 0
