#! /bin/bash
#
# $Author: ee364e10 $
# $Date: 2015-01-14 11:04:47 -0500 (Wed, 14 Jan 2015) $ 
# $HeadUrl$ 
# $Revision: 71861 $
Num_Of_Params=$#
Param_Values=$1
echo "The program recieved $Num_Of_Param parameters and the parameter is $Param_Values"
while (( Param_Values != 0))
do
  echo "$Param_Values"
  ((Param_Values=Param_Values-1))
done
exit 0